export enum heroesActionTypes {
  LOAD= '[HEROES] LOAD',
  LOAD_SUCCESS= '[HEROES] LOAD_SUCCESS',
  LOAD_FAILED= '[HEROES] LOAD_FAILED',

  ADD= '[HEROES] ADD',
  ADD_SUCCESS= '[HEROES] ADD_SUCCESS',
  ADD_FAILED= '[HEROES] ADD_FAILED',

  DELETE= '[HEROES] DELETE',
  UPDATE= '[HEROES] UPDATE',
}
